#!/bin/bash
# if g++ test.cpp -o test.app --std=c++20 -lavformat -lavcodec -lavfilter -lavdevice -lavutil -lswscale -lswresample -Werror -Wfatal-errors; then
if g++ test.cpp -o test.app --std=c++20 -lavformat -lavcodec -lavfilter -lavutil -lswscale -lswresample -Werror -Wfatal-errors; then
	# ./test.app
	./test.app input.mov output.webm
else
	echo "Compilation failed. Unable to execute ./test.app."
fi